DROP TABLE IF EXISTS RESULTAT_MATCH;
DROP TABLE IF EXISTS POULE;

DROP TABLE IF EXISTS MATCH_;
DROP TABLE IF EXISTS FEUILLE_MATCH;
DROP TABLE IF EXISTS TYPE_MATCH;

DROP TABLE IF EXISTS TIREUR;
DROP TABLE IF EXISTS ARBITRE;

DROP TABLE IF EXISTS ESCRIMEUR;

DROP TABLE IF EXISTS COMPETITION;

DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS ARME;
DROP TABLE IF EXISTS SAISON;
DROP TABLE IF EXISTS CATEGORIE;
DROP TABLE IF EXISTS CLUB;
DROP TABLE IF EXISTS PISTE;
DROP TABLE IF EXISTS CLASSEMENT_PROVISOIRE;
DROP TABLE IF EXISTS CLASSEMENT_FINAL;
